### ISSUE TITLE
Allow emitter override of output-path in project yaml

### ISSUE THREAD

**Issue by markcowl** [microsoft/cadl#1100]
Implementation issue for https://github.com/microsoft/cadl/issues/1087

- [ ] Hide 'output-path' compiler option in help and add new compiler option output-dir (continue to support output-path on the command line)
- [ ] Add output-dir option for each emitter.  Allow specifying separate output-dir setting for each emitter on command-lin (emitter-name.output-dir), and in project yaml that overrides the compiler option.
  ``` yaml
  emitter-name:
    output-dir: localDir1/localDir2
  ```

**Comment by tjprescott** [comment]
What is the triage status of this one? We are hoping to showcase running a single `cadl compile .` to generate all artifacts simultaneously at sprint review on 10/17 and this would be very valuable to show the output is tidy. Otherwise it all gets mixed together in `cadl-output` like toys in a toybox, which sort of necessitates running `cadl compile . --emit=foo --output-path=bar`.

**Comment by bterlson** [comment]
@tjprescott this is something that we want to tackle but it is unfortunately a little wrapped up in some other cleanups we want to do in this space (e.g. replacing `path` with `dir` or `file` depending on which it means and enabling parameter interpolation). For the purposes of your demo, I would suggest updating any emitters you want to show to take a `output-dir` parameter, and hopefully when we add it you will at worst just have to delete the code you added to define that parameter in your `lib.ts`.
