### ISSUE TITLE
`--option` should emit diagnostic if using an unknown emitter

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1211]
`--option @azure-tools/foo.myoption=123` could easily do a typo on the emitter name and right now we silently ignore the issue

**Comment by tjprescott** [comment]
We should also update the documentation here to use _specific_ syntax, not placeholder syntax:
https://microsoft.github.io/cadl/docs/configuration/#--option

While I can't get this feature to work even with specific syntax, the fact that the documentation is vague placeholders did not help.

**Comment by tjprescott** [comment]
Might also be handy to know that if using this in VSCode debugger to test things (which is what I was doing), this is the syntax you need to use:
![image](https://user-images.githubusercontent.com/5723682/197573596-da44a2ed-8fe1-4f8c-bd56-edad71ea3b41.png)

If debugging locally, if using a path to the emitter instead of a name, in all of your options, you must use the same path, instead of a name.

**Comment by markcowl** [comment]
est: 2
