### ISSUE TITLE
What should we do about doc comments errors

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#1439]
Discovered as part of https://github.com/microsoft/cadl/issues/1419

The following code 
```
/**
 *  p@55w0rd 
 */
model BasicAuth {}
```

cause an identifier erorr.

Problems with this right now:
- we only parse docs in the IDE not in cadl compile so you don't get ci validation for it
- because it is an error it still stop the compilation flow from moving forward(doesn't run `onValidate` and `emitters`) See #1440

**Comment by nguerrera** [comment]
I think it would be reasonable to say that doc comment parse errors are warnings. This is what csc does.

I think right now the only error possible is non-identifier char after @. We might also consider recovering by taking the @ into the text or parsing the tagName as "" instead of scary <missing identifier 1> or by generalizing identifier chars allowed there.

**Comment by timotheeguerin** [comment]
Action to move forward:
- [ ] make it a warning with better code
- [ ]error recovery treat it as text(ignore the `@` and keep reading as content)

**Comment by nguerrera** [comment]
This is small enough that I think we can just do it. It was tagged small group discussion and that was done. I will remove design tag and go ahead.
