### ISSUE TITLE
Consider changing 'mixes' keyword to something clearer

### ISSUE THREAD

**Issue by daviwil** [microsoft/cadl#318]
I was talking to Peter today and he brought up a good point that 'mixes' might not be the most obvious word that someone would expect to type to get the behavior that this keyword provides.  Other options that came up:

- adds
- extends
- includes

Is it worth discussing whether another name might be more appropriate before we start promoting interface-based modelling heavily?

**Comment by bterlson** [comment]
Definitely worth discussing. I don't like `mixes` that much. The reason we didn't go with `extends` is because the semantics we have now don't align with class extends (we aren't establishing some nominal type hierarchy). Since it's basically spread but for interface members, we went with mixes, but we didn't think very hard about it.

**Comment by markcowl** [comment]
- have a syntax review

**Comment by daviwil** [comment]
Approved to use `extends` keyword instead, implementation tracked by issue #481.
