### ISSUE TITLE
Duplicate decorators create an invalid source location error

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#382]
Having 2 libraries or js files defining the same decorator with no namespace cause a duplicate decorator error but the source location cannot be resolved 

Errors: 
```
<unknown location - cannot obtain source location of unbound node - file bug at https://github.com/microsoft/cadl>:1:1  - error duplicate-symbol: Duplicate name: "getDec"
<unknown location - cannot obtain source location of unbound node - file bug at https://github.com/microsoft/cadl>:1:1  - error duplicate-symbol: Duplicate name: "getDec"
```

Repro

In `lib1.js` and `lib2.js`
```js
export function $dec(){}
```

In `main.cadl`
```cadl
import "./lib1.js";
import "./lib2.js";
```

**Comment by timotheeguerin** [comment]
Hhm this is because those function might be used by projection @bterlson? We might be a little too flexible here on what we load.

**Comment by bterlson** [comment]
With no namespace, and without projections, wouldn't you expect an error (though probably with some useful source location)?

**Comment by timotheeguerin** [comment]
Yeah if the function is actually meant to be used in projections. I am more worried that a library would export too much things that are meant to be used for consuming the library. Like the getter for the decorator data

**Comment by bterlson** [comment]
I see. In your example, there is a $ prefix, so was wondering if the issue was the error itself or the fact that binding JS functions in cadl makes the error more likely.

In the fullness of time I don't expect there to be much difference between APIs you might call in projections vs. APIs you might call only in a JS library scenario, but it is worth discussing how to include/exclude functions from being bound into cadl.

**Comment by timotheeguerin** [comment]
sorry for the confusion I replied on the wrong issue meant to talk about this one https://github.com/microsoft/cadl/issues/384
