### ISSUE TITLE
Way to opt-in for js functions available to projections

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/cadl#396]
From #384 
Currently all exported JS function from a library are loaded, bound and made available to the projection engine. This could cause unwanted conflict.

A library might be exporting different set of functions:
1. Decorators
2. Cadl hooks(`$onEmit`)
3. Projection function
4. Getter for consuming the library from an emitter
5. Other helper methods

Scenario 4. and 5. are things that could easily be conflicting across library and then prevent those libraries from being imported together with no way around.

We currently have the decorator opt-in with the `$` prefix. Should maybe be a similar system for projection functions.

**Comment by bterlson** [comment]
It is worth noting that there is perhaps significant overlap between 3 and 4. For example, the version projections make extensive use of "addedAfter" and friends which could be useful from JS as well. Likewise I could see projections making use of `getVersions`  in custom version projections.

It may be that having an opt-out rather than an opt-in is the right approach? It also might be possible to only project functions which have the proper signature for projections (i.e. take a Program as a first argument).

**Comment by timotheeguerin** [comment]
what if we just have every library have a `export const $namespace = "Foo.Bar"` which is the base namespace unless specified on the function. Would make it quite easy to scope everything and forgetting to put a new funciton in the namespace wouldn't happen.

**Comment by timotheeguerin** [comment]
Actually discovered that this already exists with `export const namespace`. I think then we might just want to have some linter for libraries that can have a set of best practices before publishing

**Comment by timotheeguerin** [comment]
I think that also might be solved completely by the decorator declaration with either way we go forward with it.
