### ISSUE TITLE
The "get" method of ResourceOperations should not have a "204" response

### ISSUE THREAD

**Issue by mikekistler** [microsoft/cadl#417]
The following Cadl file
```
import "@cadl-lang/rest";
import "@cadl-lang/openapi3";

using Cadl.Rest;
using Cadl.Rest.Resource;

namespace Things {
  model Thing {
    @key
    @segment("things")
    thingId: string;
  }

  model Error {}

  interface Things mixes ResourceOperations<Thing, Error> {}
}
```

Generates an OpenAPI 3 definition where the "get" on "/things/{thingid}" has both a "200" and a "204" response.  I don't think the "204" response should be generated.

**Comment by bterlson** [comment]
I think it's because it thinks the Error model is a regular model with no content. If you put `@error` on the error model I suspect you'll get something you like better.

**Comment by mikekistler** [comment]
That seems so logical!  Unfortunately it does not solve the problem. The openapi is exactly the same with and without `@error`.

**Comment by bterlson** [comment]
It appears the problem is that the Error model is empty.

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOw0KdXNpbmcgQ2FkbC5SZXN0xAVvdXJjZTsNCg0KbW9kZWwgVGjEI3sNCiAgQGtlecQIdMQTSWQ6IHN0cmluZzsNCn3EMEBlcnJvciDGN0XFDMU3Ly8gYWRkIHByb3BlcnR5IGhlcmUgYW5kxkhzIHdvcmvFQ2ludGVyZmFjZcZ1cyBtaXhlcyDoAJVPcGVyYXRpb25zPMUgLMZlPiB7fQ%3D%3D)

**Comment by mikekistler** [comment]
Okay ... that really is logical and does solve the problem.  I should have seen that.
