### ISSUE TITLE
Create a "readOnly" decorator for openAPI to take the place of visibility("read")

### ISSUE THREAD

**Issue by mikekistler** [microsoft/cadl#453]
Current work to simplify/clarify request and response body/metadata will almost certainly require redefining the way visibility is interpreted, so we should prepare for that by eliminating the current "special case" interpretation of `visibility("read")` in the openapi emitters as "readOnly".  This can be done by introducing a new `readOnly` decorator in the opeapi library that specifically means that a property should have `readOnly: true` in the emitted openapi.

**Comment by bterlson** [comment]
Some concerns for discussion:

1. Explaining the difference between visibility("read") and readOnly/writeOnly seems difficult and subtle.
2. In practice users will need both. And assuming models get emitted to other protocols with a notion of readOnly, we now have three or more readonly decorators on model properties.
3. The intention of the visibility framework was to provide an affordance that subsumes notions of readonly and writeonly in a way that generalizes to more complex, possibly protocol-specific lifecycles. readonly is a duplication of a small slice of visibility. We should prove that the visibility framework doesn't work (and then likely remove it) before introducing a protocol-specific notion of the concept.
4. I don't see any issues with the current implementation of applying 'readonly' when visibility('read') is set, to me those read like the same thing.

**Comment by nguerrera** [comment]
The OpenAPI spec says this:

"Declares the property as "read only". This means that it MAY be sent as part of a response but SHOULD NOT be sent as part of the request. "

That sounds like the same use case as visibility("read").  Cadl should aim to provide a single abstract concept where possible that gets lowered down to the right thing in OpenAPI rather than require adding OpenAPI-specific decorators.

I think a main difference right *now* is that you have to actively do something to apply visibilities other than "read" while visibility("read") is interpreted by the emitter. However, the main metadata proposal proposes that the emitter applies visibility for all the lifecycle operations. *If* we end up going with that proposal, it then becomes perfectly natural that it would apply "read" automatically. And then you could say it is simply an emit optimization that it determines that while it may have to emit Thing and ThingUpdate. It can collapse Thing and ThingRead into just Thing by making the properties that would have been exclusive to ThingRead `readonly` on Thing.

So I'm not comfortable adding this decorator while we're still looking at how visibility is handled all-up. 

Then I have the somewhat separate concern that I hate the terms "read" and "read only" in this context. It is terribly confusing. It reminds me of "yours" and "theirs" when resolving merge conflicts. Who's who? Sometimes I'm "them" and "they" are me and I want to find a new career. "Read" and "write" are equally a question of perspective: Client writes a request, server reads it, server writes a response, client reads it. I would prefer if we didn't perpetuate this "read/write" terminology in Cadl. I'd like to see visibility("request") and visibility("response"). replace "read" and "write". If we have two different places where we use this notion of "read" it will be twice as hard to address this confusion and twice as confusing.

**Comment by mikekistler** [comment]
@bterlson 

> Explaining the difference between visibility("read") and readOnly/writeOnly seems difficult and subtle.

The [_current_ documentation for `@visibility` ](https://github.com/microsoft/cadl/blob/main/docs/tutorial.md#visibility-decorators) gives __no semantics whatsoever_ to "read" other than how _the Cadl author_ chooses to define it when applying the `@withVisibility` decorator.  So there is no subtlety here at all.  `@visibility("read")` means what the Cadl author intends, and `@readOnly` means _very specifically_ that in the generated OpenAPI the property will have the `readOnly: true` attribute.  Personally I find this crystal clear.

But perhaps the current documentation for `@visibility` is WRONG and we would like to attach specific meanings to certain values of `@visibility`.  In [your proposal for handling metadata](https://gist.github.com/bterlson/88871dd5bed51df6a8e483a21205a77f) you proposed some specific values for `@visibility` -- "query", "create", "update", "delete", "list", "read" -- have a specific meaning: "whether a field is present in the model for a given part of the lifecycle". With this definition, I don't think `@visibility("read")` means that a property is marked as `readOnly: true` -- at least that's not how I interpreted it.  This is why I said in the description:

> Current work to simplify/clarify request and response body/metadata will almost certainly require redefining the way visibility is interpreted,

But if I misunderstood your proposal then let's just clarify that and we can put this issue on hold until the details of that proposal are worked out.

**Comment by mikekistler** [comment]
@nguerrera and @markcowl I need to point out that the behavior of `@visiblity("read")` is currently not documented anywhere, and the semantics of "read" (as I pointed out above) are purely up the Cadl author to determine (based on the current documented behavior of `@visibility`).

So I dispute the claim that `readOnly: true` is "the same use case as visibility("read")" or " a concept we have covered at a higher level".

If you believe differently, please point to the documentation that disproves my point.

**Comment by nguerrera** [comment]
Here's my citation: @bterlson, one of the inventors of Cadl and `@visibility`, wrote the following just a few lines up:

> The intention of the visibility framework was to provide an affordance that subsumes notions of readonly and writeonly in a way that generalizes to more complex, possibly protocol-specific lifecycles

Cadl is still a work-in-progress. There will be things that aren't captured in documentation, or things we wish to be true eventually that aren't quite true yet. We should discuss the experience we want to build, build it and document it.  Our documentation isn't mature enough to be used like a legal text.

**Comment by mikekistler** [comment]
I'm not asking for legal text. But I do think this behavior should be documented, as `readOnly: true` is used all over the place in Azure (overused actually IMHO).  But I guess until we actually figure out how we want it to work maybe it is best left undocumented.

**Comment by nguerrera** [comment]
Metadata proposal is implemented now and treats `readOnly: true` as an optimization. If it can avoid creating a separate suffixed schema by using `readOnly: true`, it will. There is no need for a separate decorator.

**Comment by markcowl** [comment]
completing closed issue
