### ISSUE TITLE
[IDE]  Relative Path Completion

### ISSUE THREAD

**Issue by Jg1255** [microsoft/cadl#621]
Cadl needs the implementation of Relative Path Completion.

**Comment by markcowl** [comment]
@Jg1255 Where are you not seeing relative path completion?  Is this in particular elemtns in a cadl spec (like import)?  In cli options?  Somewhere else?  I ask because many of these (imports, for example) do support relative paths.

If you cna provide details on where you see a lack of relative path completion, and what kind of relative path you are providing, that would be helpful.

**Comment by nguerrera** [comment]
Fixed by #650
