### ISSUE TITLE
Add Uri base type

### ISSUE THREAD

**Issue by annelo-msft** [microsoft/cadl#654]
Add `Uri` to the list of [supported built-in types](https://github.com/microsoft/cadl/blob/main/docs/tutorial.md#built-in-models).

This is to support what is represented with [the string format `uri` in swagger](https://swagger.io/docs/specification/data-models/data-types/#format).

**Comment by mikekistler** [comment]
I think we want two new special string types:
- "url" - for a Universal Resource Locator (a special case of URI but important to distinguish)
- "uuid" - for Universal Unique Identifier

The autorest and openapi3 emitters will emit "format: url" and "format: uuid" for these, respectively.

**Comment by markcowl** [comment]
Link to PR: https://github.com/microsoft/cadl/pull/808

**Comment by mikekistler** [comment]
Discussed in the Cadl design meeting on 8/4 and decided that the `ResourceLocation<T>` type defined in the Rest library should be sufficient (and actually better) than simply defining a value as "type url".

The cadl-autorest emitter should be updated to add "format: url" for properties of type `ResourceLocation<T>`.

We'll consider an intrinsic type for uri/url in the future when we have better information about use cases, etc.

**Comment by tjprescott** [comment]
@mikekistler from the most recent ARB review session, Ted pointed out how for "Endpoint" in the `@server` decorator needs to be specified as something more than just a string because of how other languages will use it. That does not seem to fit the scenario where `ResourceLocation<T>` is sufficient.

**Comment by annelo-msft** [comment]
Yep, we have a related conversation happening in this cadl-azure issue: https://github.com/Azure/cadl-azure/issues/1785

**Comment by mikekistler** [comment]
For this special case I think `@format("url")` should work. Is there any reason we need more than that?

**Comment by tjprescott** [comment]
> For this special case I think @format("url") should work. Is there any reason we need more than that?

Not that I know of. Should we reopen this issue?  I don't have that great power 😆

**Comment by annelo-msft** [comment]
I also think we should reopen this issue, or track resolution for code-gen at https://github.com/Azure/cadl-azure/issues/1785

**Comment by mikekistler** [comment]
@annelo-msft What problem needs to be solved that cannot be solved with `ResourceLocation<T>` or `@format("url")`?

I'm happy to reopen this issue if there is a clear statement of the problem.

**Comment by tjprescott** [comment]
Well, there's already an issue open to get rid of or strongly dissuade use of `@format` so it would be odd that we would need to use that for uri, and `ResourceLocation<T>` doesn't work because there's no resource to speak of in this case. The resource is the service account, which probably isn't modeled in Cadl.

**Comment by annelo-msft** [comment]
I think we have a few cases where we would use a Uri type, or alternative:
- To designate that an endpoint is a Uri
- To designate that a model property is a Uri: [BlobDownloadDetails.CopySource](https://apiview.dev/Assemblies/Review/a9af7ed90fe84a649de0b47c989eaf07#Azure.Storage.Blobs.Models.BlobDownloadDetails)
- To designate that a parameter is a Uri: [StartRecgnizeXxFromUri](https://apiview.dev/Assemblies/Review/f1b0fcc99bc34097b300e9d965a5904c#Azure.AI.FormRecognizer.FormRecognizerClient)

If we provided this type, we could provide a specific decorator/other for it to address Uri encoding: https://github.com/microsoft/cadl/issues/851

**Comment by mikekistler** [comment]
I think `ResourceLocation<T>` is a better way to accomplish all of the above. Why is it not sufficient?

**Comment by annelo-msft** [comment]
@mikekistler, I'm not seeing that clearly, but that doesn't mean it's not the right answer.  Could you help me understand by providing examples of what it would look like to use `ResourceLocation<T>` in each of those cases?

**Comment by mikekistler** [comment]
`CopySource` can be:
```
    copySource: ResourceLocation<Blob>;
```

The FormRecognizer case is a great example of the benefit of using `ResourceLocation<T>` over just `URI`, because the different URI types will be explicit on what they locate:
```
    businessCardUri: ResourceLocation<BusinessCard>;
    identityDocumentUri: ResourceLocation<IdentityDocument>;
    etc.
```

Make sense?

**Comment by annelo-msft** [comment]
I see, so it works when the URI is the location of a resource, that makes sense.
How would this work in the case of the URI needing to represent the service endpoint?
Is it possible there are other cases where the URI doesn't correspond to a resource, or potentially indicates a resource that isn't represented in the services defined model schema?

**Comment by mikekistler** [comment]
The `endpoint` parameter we generally use in `x-ms-parameterized-host` seems like a special case to me. There are a couple ways to handle it. I suggested one above, which is to add `@format("url")` on it. Another possibility is to define it as `ResourceLocation<any>` -- I think that should work.

We're trying to avoid having multiple ways of doing things, since that just confuses users about which one they should use. If we provide _both_ a `url` type and `ResourceLocation<T>`, we invite that confusion. So if we can get by with `ResourceLocation<T>` for all (or nearly) all use cases, we can avoid that confusion.

**Comment by annelo-msft** [comment]
I think @JeffreyRichter had recommended moving away from `@format`, which sounded like a good idea to me.  `ResourceLocation<any>` feels a little awkward given it would have to bypass templating.  Would we be concerned that resource means something specific in REST APIs and a service endpoint isn't really a resource?  Or do we understand "ResourceLocation" as "UniformResourceLocation" with the "Uniform" dropped?

I don't have full context on `ResourceLocation<T>`, so I think I still don't understand what value it provides over a `Uri` type.  Is it used for route generation, is that the reason for it?  Would it make sense to provide an untemplated version for the root URI?

**Comment by mikekistler** [comment]
@annelo-msft I've given all my reasoned arguments for avoiding adding a `url` type. If have have been unconvincing then please ask @markcowl  to schedule this into an upcoming Cadl Design meeting and you can come make your case to the team.

**Comment by annelo-msft** [comment]
Is it not possible to share the thinking behind `ResourceLocation<T>`?

I know @tg-msft had some thoughts on the matter as well.

**Comment by mikekistler** [comment]
`ResourceLocation<T>` means the location of the resource of type `T`, which for HTTP protocols means a URL for the resource. Sorry if that was not clear from the earlier discussion. Was that all I needed to say?

**Comment by tg-msft** [comment]
I don't grok the `ResourceLocation<T>` concept.
- Would we use `ResourceLocation<string>`?  What does it mean for `string` to be a resource?
- Or do I have to create a dummy `T` just to have a URI to it?  It muddies the water when we include URIs to things that aren't resources in Azure, like a blob copy source that's effectively any accessible URI, if we have to create an empty `model BlobCopySourceResource { }` just to get code to generate properly in strongly typed languages.

I also don't understand how this is different than something like `safeint`.  You could make the same argument that we should just put `@format("json")` or `JsonFriendly<int>`, but `safeint` gets a primitive.  You can't pass an arbitrary `unsigned long` to something expecting a `safeint`, much like you can't pass "Hello World" to something expecting a `url` or a `uuid`.

Where does `ResourceLocation<T>` live in the stack?  If we partially expand all the ACDPBBs _(Azure Core Data Plane Building Blocks)_ down to just the "REST layer" for reviewing will I still see things are URIs if we mark them as `ResourceLocation<string>`?

**Comment by markcowl** [comment]
The idea behind `ResourceLocation<T>` is to represent a url that, when followed with a GET (in http, potentially other actions in other protocols), returns a typed resource. This is used for example in APIs that present paged responses with URLs to previous and next pages, or for links to dependent or associated resources. 

I think we have identified two scenarios where there isn't a pattern:

1. Strings used to construct Urls (url parts) that are represented as 'Uri' in some languages (e.g. Service Endpoint).  I think that some of these may actually be Urls (https://myservice.com, but some may be simply authority or partial authority [myaccount.vault.azure.net, blob.core.windows.net]).
2. Full Urls that return a resource unknown to the specification (links to external service resources, documents, or the like)
3. [Also URNs, but I don't think any of the cases require support for this, and not sure if this is a real need]

For (1), I am not sure that ResourceLocation is the right pattern, as the purpose in http is not to follow the Uri with a GET to retrieve a resource. As far as I can tell, the purpose is to mark these fields as strings used to construct Uris for language generators that support types like the C# Uri. 

For (2), `ResourceLocation<unknown>` or `ResourceLocation<any>` or `ResourceLocation<Record<any>>` would seem to make sense, though we might decide on a particular type to use in Azure APIs instead of these generic types.

I will put this on the design agenda for this week, and will put this on the agenda for the DPG sync this week (9/13).

**Comment by markcowl** [comment]
@tg-msft  `ResourceLocation<T>` is a template.  The actual type is string, meaning that the url is actually represented as a string.  The template adds additional decoration (corresponding to the type argument 'T', which emitters can use to decide how to represent and document the field.
