### ISSUE TITLE
Breaking changes: August release

### ISSUE THREAD

**Issue by nguerrera** [microsoft/cadl#728]
Starting an issue to track August release notes about breaking changes.

#726

### Unannotated operation parameters

A single unannotated (not marked `@query`, `@header`, `@body` or `@path`) operation parameter will now become a property of the request body rather than have its type define the request body. This allows defining the body with multiple unannotated parameters, which can include unannotated properties that are spread into parameters. (Previously, more than one unannotated parameter was an error.)

For example, the following used to define a request body of type `string`,  but now defines a request body that is an object with a property named `body` of type string.

``` cadl
op create(body: string): void;
```

To get the previous behavior, the parameter now needs to be explicitly marked with `@body` as in:

```cadl
op create(@body body: string): void;
```

**Comment by nguerrera** [comment]
#782

## OkResponse is now non-generic

Previously OkResponse took an argument for the body type. Now it is non generic like the other XxxResponse types. Alone, it implies a status code of 200 with no body. 

Since 200 is the default status code for non-empty bodies, you can usually replace `OkResponse<T>` with simply `T`. If you wish to be more explicit, you can use `OkResponse & T`.


```
op get(id: string): OkResponse<Pet>
```

Can be:

```
op get(id: string): Pet;
```

Or:

```
op get(id: string): OkResponse & Pet;
```

In certain situations where the body type is not (necessarily) a model, you will need to use the new `Body<T>` type. For example.

```
op list(): OkResponse<Pet[]>
```

Can become:

```
op list(): OkResponse & Body<Pet[]>

```


But again since 200 status code is used by default, this could also be:

```
op list(): Pet[];
```

Another situation where you may need `Body<T>` is where you built generic models based on OkResponse<T> such as
```
model MyResponse<T> {
...OkResponse<T>
 @header example: string;
}
```

Here we can't be sure that T is a model. It might be instantiated as MyResponse<string[]>. Then we can replace it as follows:

```
model MyResponse<T> {
   ...OkResponse;
   ...Body<T>;
    @header example: string;
}
```


In general, the prior `OkResponse<T>` is equivalent to `OkResponse & Body<T>` now or, equivalently, `{ ...OkResponse, ...Body<T> }`. And in practice  there are many situations where you can leave out OkResponse altogether and use plain `T` rather than `Body<T>`.

See also https://github.com/microsoft/cadl/blob/main/docs/tutorial.md#request--response-bodies

**Comment by timotheeguerin** [comment]
If #800 make it in

## Route resolution changes

Resolving the routes now follow the following logic:

- if there is a service namespace specified
  - only take the operation and interface under that namespace(recursively)
- if not:
  - only take the operation and interfaces defined at the root (DO NOT look into namespaces)

## Action if applicable
- If cadl spec was under a namespace without `@serviceTitle` add it otherwise no routes will be resolved.
- If add another namesapce not under the service namespace. Move it under the service namespace.

## Cases

### Operation at the root

```cadl
op test(): void;
```

✅ Stay the same

| Before  | After   |
| ------- | ------- |
| `["/"]` | `["/"]` |

### Operation in namespace (not service namespace)

```
namespace DemoService;

op test(): void;
```

⚠️ Output stay the same but add warning that there is no routes

| Before | After |
| ------ | ----- |
| `[]`   | `[]`  |

### Operation in namespace (not service namespace) with @route

```
namespace DemoService;

@route("/")
op test(): void;
```

⚠️ Now the same as previous case, no route included and emit warning

| Before  | After |
| ------- | ----- |
| `["/"]` | `[]`  |

### Operation in service namespace

```cadl
@serviceTitle("My Service")
namespace Foo;

op test(): void;
```

✅ Stay the same

| Before  | After   |
| ------- | ------- |
| `["/"]` | `["/"]` |

### Operation in other namespace than service namespace

```
import "@cadl-lang/rest";

using Cadl.Http;

@serviceTitle("My Service")
namespace Foo {
  @route("in-service")
  op test(): void;
}

namespace MyLib {
  @route("my-lib")
  op test(): void;
}
```

⚠️ Other namespace routes are not included anymore

| Before                      | After             |
| --------------------------- | ----------------- |
| `["/in-service", "my-lib"]` | `["/in-service"]` |
