### ISSUE TITLE
Is there a way to hide building blocks during generation?

### ISSUE THREAD

**Issue by rakshith91** [microsoft/cadl#817]
Related to https://github.com/microsoft/cadl/issues/810

In the example, is it possible to hide the generation of enum which we don't want - since it's just a building block

```
enum AppConfigurationEventTypes {
  modified;
  deleted;
}

model AppConfigurationBase<TResource> {
  @doc("The key used to identify the key-value that was {name}.", TResource)
  key?: string;
  @doc("The label, if any, used to identify the key-value that was {name}.", TResource)
  label?: string;
}
@doc("Schema of the Data property of an EventGridEvent for a Microsoft.AppConfiguration.KeyValueModified event.")
model AppConfigurationKeyValueModifiedEventData is AppConfigurationBase<AppConfigurationEventTypes.modified>;

@doc("Schema of the Data property of an EventGridEvent for a Microsoft.AppConfiguration.KeyValueDeleted event.")
model AppConfigurationKeyValueDeletedEventData is AppConfigurationBase<AppConfigurationEventTypes.deleted>;
```

**Comment by markcowl** [comment]
@rakshith91  which generator is emitting the enum?

**Comment by allenjzhang** [comment]
+1 on Mark's question. For OpenApi3, since the enum type is not referenced in the model properties, it is not emitted. See [example](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3Jlc3QiOwrTGm9wZW5hcGkzIjsKCkBzZXJ2aWNlVGl0bGUoIldpZGdldCBTxhUiKQpuYW1lc3BhY2UgRGVtb8cYOwp1c2luZyBDYWRsLlJlc3TNEUh0dHDIEU9wZW5BUEk7CgplbnVtIEFwcENvbmZpZ3VyYXRpb25FdmVudFR5cGVzIHsKICBtb2RpZmllZDsKICBkZWxldMQLfQoKbW9kZWzRPUJhc2U8VFJlc291cmNlPsVCQGRvYygiVGhlIGtleSB1c2VkIHRvIGlkZW50aWZ5IHTGGS12YWx1ZSB0aGF0IHdhcyB75ADmfS4iLCDJTykKIMQqPzogc3RyaW5n5ACTyl1sYWJlbCwgaWYgYW55LN9o32ggxk7LagovLyAgdHlwZTrKKOQBCOYAgFNjaGVtYSBvZsVmRGF0YSBwcm9wZXJ0ecQVYW4g5QFWR3JpZMUJIGZvciBhIE1pY3Jvc29mdC7wAUguS2V5VuQAqU3nAX8gZcQ4LiIp9wF50DDFZ%2BUAiWlz0S3lAab6Afgu6AH0PuQCjf8A4f8A4f8A4XVlROYCVP8A4OkA4Mcv%2FwDf%2FgDf5wLH5QDe5ANab3AgcmVhZChAcGF0aCBpZOgB9ik6%2FwFn6wCIOwpAcG9zxUzECN9M%2FQDTOwo%3D). Even it is referenced by uncomment line 21, the enum is defined inline. 

I wonder if your the original intention is better modeled by using `@discriminator`

**Comment by markcowl** [comment]
@rakshith91 we will have to close this issue at EOW, please respond with the emitter where you are seeing this behavior.

**Comment by rakshith91** [comment]
@markcowl sorry for the late response. I'm unable to find an example where enum is generated. 

I'll close this issue for now. Will re-open if necessary
Sorry for the bother
