### ISSUE TITLE
Consider simplified docs for operations and leverage routes for path arguments

### ISSUE THREAD

**Issue by Petermarcu** [microsoft/cadl#927]
Looking at some concrete examples of some rest layer cadl I find things like this quite often:

```
  @summary("Check if there are any client connections connected for the given user.")
  @doc("Check if there are any client connections connected for the given user.")
  @route("/api/hubs/{hub}/users/{userId}")
  @head
  UserExists(
    @doc("""
Target hub name, which should start with alphabetic characters and only contain
alpha-numeric characters or underscore.
""")
    @path
    hub: string,

    @doc("Target user Id.")
    @path
    userId: string,
  ): ErrorDetail | void;
```

Observations:
- I don't understand why we need summary and doc with the same string.
- The docs directly on the parameters significantly reduce readability.
- the @path on the params is redundant with the specification in the route.

I'd much rather be able to write something like this:

```
@doc("""Check if there are any client connections connected for the given user.
        {hub} Target hub name, which should start with alphabetic characters and only contain
            alpha-numeric characters or underscore.
        {userId} Target user Id. )
@route("/api/hubs/{hub}/users/{userId}")
@head UserExists(hub: string, userId: string): ErrorDetail | void;
```

I suspect this would just mean:
- Adding support in the doc decorator to apply parts of it to arguments 
- It would require the @route decorate be able to add the @path to the args. 
- We just have to figure out what the use case is for @summary and @doc together.

**Comment by Petermarcu** [comment]
Another interesting observation here is the fact that the text of one of the parameters is there to spell our the constraint on the string. I wonder if we could generate that text in some way from format decorator on the param? "which should start with alphabetic characters and only contain
alpha-numeric characters or underscore."

**Comment by allenjzhang** [comment]
Types of documentation string:
1. Service Enduser (final API documentation)
2. Cadl spec writer (building bloc such as library base class/operations,  TrackResource, ResourceOperation usages)

Questions:  @doc vs.  `//` comment bloc

String templates (see other issue on this topic) to enable docs on sub-elements in parent elements
Emit summary from doc if explicit summary isn't provided?

Work item:
.
- Infer @path from @route token so that @path is optional.
- general string template support
-

**Comment by allenjzhang** [comment]
#1973

**Comment by allenjzhang** [comment]
Proposal a complete multiline format with property/parameters template reference.

- template token on a new line with no proceeding  

  - For models, template token refers to properties
```
@doc("""
  A person
  
  {name}: The person's name
  {age}: The person's age
""")
model Person {
  name: string;
  age: uint8;
}
```
  - for operations, template token refers to parameters
```
 @doc("""
  Rename a person.
  
  {from}: the current name of the person
  {to}: the new name for the person
  {self::returnType}: returns the person that was renamed.
""")
op rename(from: string, to: string): Person;
```
  - for templated types, token refers to Template parameters
```
@doc("""
  A resource model
  
  {TResourceProperties}: The resource property template type that goes with the resource
""")
  model ResourceModel<TResourceProperties>
```
- Specialized Tokens:
  - Operation returns  `{self::return}"
  - Any others?

Open questions:
- The current proposal only addresses the token to field reference issue. Do we need similar to JSDoc `@xxx` (maybe a subset) to add more classifications. This may remove the need to use specialized tokens as well as separate the template arguments doc from regular property doc.

**Comment by markcowl** [comment]
@allenjzhang @nguerrera Please add your latest writeups

**Comment by nguerrera** [comment]
Also linking @bterlson's string template sketch that lines up with @allenjzhang's notes above: https://gist.github.com/bterlson/a23d1bd5f8f8f5afec3eb5bf937b93b6

**Comment by allenjzhang** [comment]
Let's start with the string interpolation without JSDoc style token. The proposal and sample are as writeup above. 

As for the API doc and dev doc from library, Nick has a good proposal with `extern dec` that can be unified with multi-line @doc proposal above.

**Comment by nguerrera** [comment]
I didn't have time to get into this when we spoke yesterday, but it is not possible to unify everything with `@doc` documentation. This is covered in the linked developer doc proposal: there are entities (building blocks) that exist only at Cadl-authoring time and these entities cannot have decorators, nor should they. If we tried to use `@doc` on an `extern dec`, that would mean that we were decorating decorators! This would greatly complicate things. I don't think it makes sense to reify these decorators in the modeling of entities that can be decorated just so that we can document them. 

So, something other than decorators is needed to document decorators (and aliases, functions, etc.).  But then the problem is that people see the (subjectively) nicer syntax for those cases and invariably question why they can't use it to document API. And I sympathize with that.

It's incredibly difficult to explain the distinction between these two scenarios. They are technically very real and very different, but we often find ourselves selling Cadl to an audience that is only interested in reading inline API documentation that looks pretty and familiar. And it increasingly feels to me like I'm losing that sale when I get into explaining all this. So I'm thinking about ways to blur this distinction to the extent possible without compromising functionality.

I believe the only way to unify the syntax is in the other direction: towards doc comments for everything: API end-user and Cadl building block consumers. My basic idea is that some doc comments (or perhaps some portions of doc comment) will still compile down to decorator application so that they can still benefit from sidecars, decorator composition, and so on. I will try to write this up in a bit more detail.

**Comment by nguerrera** [comment]
I wrote up the idea I had here:

https://gist.github.com/nguerrera/a48a3d8f005eb5322683fc5ddc48c363

**Comment by allenjzhang** [comment]
Commented on Nick's gist. Post here for visibility as well.
 
Having distinct parts come out looks a lot busier. I do agree that the comment block style looks a lot more familiar in code, but one of the goals is to be able to easily integrate out for doc which will be harder to do. We have already established the need for @doc for Cadl spec documentation purposes. I haven't seen good scenarios/reasons that @doc can't be used.

**Comment by nguerrera** [comment]
> Having distinct parts come out looks a lot busier.

Can you elaborate on this? I don't know what this means.

> I haven't seen good scenarios/reasons that @doc can't be used.

You mean apart from the developer documentation scenarios, right? You're saying we should continue with POR of doc comment for things like decorators and @doc for API docs?

**Comment by allenjzhang** [comment]
Remaining work item: 

https://github.com/microsoft/cadl/issues/1399

**Comment by nguerrera** [comment]
Reopening as this is what tracks the linked proposal on unification.

**Comment by nguerrera** [comment]
But also noting that the prereq developer docs proposal (Design: #131, Implementation: #719, PR: #1313) is done. 😁

**Comment by nguerrera** [comment]
I am not sure if this should be closed, do we have implementation issue(s) for the unification yet? cc @timotheeguerin.

**Comment by nguerrera** [comment]
I think maybe we should close #1399 and replace it with what we discussed before the holidays.

**Comment by timotheeguerin** [comment]
I didn't create an issue, I can do that now
